@echo off
rem OpenClaw Gateway (v2026.1.29)
rem 确保 UTF-8，避免中文/日文路径乱码 (read/exec 工具)
chcp 65001 >nul 2>&1
set PATH=C:\Users\wengzheng\AppData\Local\Programs\Python\Python313\Scripts;C:\Users\wengzheng\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-8.0.1-full_build\bin;C:\Users\wengzheng\miniconda3;C:\Users\wengzheng\miniconda3\Library\mingw-w64\bin;C:\Users\wengzheng\miniconda3\Library\usr\bin;C:\Users\wengzheng\miniconda3\Library\bin;C:\Users\wengzheng\miniconda3\Scripts;C:\Users\wengzheng\miniconda3\bin;C:\Users\wengzheng\miniconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.0\bin\x64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.0\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA\CUDNN\v9.8\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\libnvvp;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn;C:\Program Files\Microsoft SQL Server\160\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files\Microsoft SQL Server\160\DTS\Binn;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;c:\Users\wengzheng\AppData\Local\Programs\cursor\resources\app\bin;C:\Program Files\nodejs;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Users\wengzheng\AppData\Local\Programs\Python\Python313;.;C:\Program Files\WinMerge;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\NVIDIA Corporation\Nsight Compute 2025.3.1;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Tailscale;C:\Users\wengzheng\AppData\Local\Programs\Python\Python311\Scripts;C:\Users\wengzheng\AppData\Local\Programs\Python\Python311;C:\Users\wengzheng\AppData\Local\Programs\Python\Launcher;C:\Users\wengzheng\AppData\Local\Microsoft\WindowsApps;C:\Users\wengzheng\AppData\Local\Programs\Ollama;C:\Users\wengzheng\AppData\Local\Programs\cursor\resources\app\bin;C:\Users\wengzheng\AppData\Roaming\npm;C:\Users\wengzheng\AppData\Roaming\Composer\vendor\bin;C:\Users\wengzheng\AppData\Local\Programs\Python\Python313;C:\PhoenixSuit
set OPENCLAW_GATEWAY_PORT=18789
set OPENCLAW_GATEWAY_TOKEN=57faef0202908f2edabf81bdf9a52dbcdfe5d441a47f7882
set OPENCLAW_SYSTEMD_UNIT=openclaw-gateway.service
set OPENCLAW_SERVICE_MARKER=openclaw
set OPENCLAW_SERVICE_KIND=gateway
set OPENCLAW_SERVICE_VERSION=2026.1.29
"C:\Program Files\nodejs\node.exe" C:\Users\wengzheng\AppData\Roaming\npm\node_modules\openclaw\dist\index.js gateway --port 18789
